name: quiz_drive
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  firebase_database: ^10.2.5
  google_sign_in: ^6.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  cupertino_icons: ^1.0.5
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  image_path: "assets/page-1/images/rectangle-TTf.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/page-1/images/google-1.png
    - assets/page-1/images/icon-signal-bars-.png
    - assets/page-1/images/icon-signal-strength-3.png
    - assets/page-1/images/ellipse-67.png
    - assets/page-1/images/ellipse-72.png
    - assets/page-1/images/arrowleft.png
    - assets/page-1/images/ellipse-73.png
    - assets/page-1/images/ellipse-69.png
    - assets/page-1/images/quiz.jpg
    - assets/page-1/images/results.jpg
    - assets/page-1/images/icon-signal-strength-3-865.png
    - assets/page-1/images/ellipse-66.png
    - assets/page-1/images/arrowleft-4gR.png
    - assets/page-1/images/messagefill.png
    - assets/page-1/images/icon-signal-bars--te5.png
    - assets/page-1/images/ellipse-50.png
    - assets/page-1/images/viewhidefill.png
    - assets/page-1/images/icon-signal-bars--AcR.png
    - assets/page-1/images/ellipse-71.png
    - assets/page-1/images/icon-battery-charge-100-full.png
    - assets/page-1/images/icon-signal-strength-3-RUu.png
    - assets/page-1/images/ellipse-74.png
    - assets/page-1/images/icon-signal-bars--5wF.png
    - assets/page-1/images/icon-battery-charge-100-full-gi5.png
    - assets/page-1/images/ellipse-70.png
    - assets/page-1/images/icon-signal-bars--x8R.png
    - assets/page-1/images/ellipse-69-yTP.png
    - assets/page-1/images/layer2.png
    - assets/page-1/images/icon-signal-strength-3-Zys.png
    - assets/page-1/images/icon-signal-bars--3ry.png
    - assets/page-1/images/menu.png
    - assets/page-1/images/icon-signal-strength-3-2cR.png
    - assets/page-1/images/arrowleft-HYD.png
    - assets/page-1/images/arrowleft-d6H.png
    - assets/page-1/images/ellipse-71-j9K.png
    - assets/page-1/images/ellipse-68.png
    - assets/page-1/images/icon-battery-charge-100-full-RNq.png
    - assets/page-1/images/ellipse-68-4e5.png
    - assets/page-1/images/ellipse-70-SLR.png
    - assets/page-1/images/frame.png
    - assets/page-1/images/arrowleft-AnD.png
    - assets/page-1/images/icon-battery-charge-100-full-Jty.png
    - assets/page-1/images/ellipse-71-Key.png
    - assets/page-1/images/ellipse-67-m1B.png
    - assets/page-1/images/icon-signal-bars--iBK.png
    - assets/page-1/images/icon-signal-strength-3-NfB.png
    - assets/page-1/images/icon-signal-strength-3-hxM.png
    - assets/page-1/images/icon-battery-charge-100-full-Vmj.png
    - assets/page-1/images/icon-signal-bars--FN9.png
    - assets/page-1/images/ellipse-74-VA1.png
    - assets/page-1/images/ellipse-73-jCm.png
    - assets/page-1/images/expanddown.png
    - assets/page-1/images/userfill.png
    - assets/page-1/images/ellipse-72-meZ.png
    - assets/page-1/images/expanddown-8s3.png
    - assets/page-1/images/ellipse-75.png
    - assets/page-1/images/layer1.png
    - assets/page-1/images/icon-battery-charge-100-full-zVF.png
    - assets/page-1/images/icon-battery-charge-100-full-TzH.png
    - assets/page-1/images/layer2-5km.png
    - assets/page-1/images/icon-signal-bars--axR.png
    - assets/page-1/images/ellipse-69-p7K.png
    - assets/page-1/images/icon-battery-charge-100-full-cPs.png
    - assets/page-1/images/frame-jzq.png
    - assets/page-1/images/userfill-9cd.png
    - assets/page-1/images/arrowleft-xdF.png
    - assets/page-1/images/icon-signal-bars--57X.png
    - assets/page-1/images/icon-signal-strength-3-yUM.png
    - assets/page-1/images/icon-signal-strength-3-fbP.png
    - assets/page-1/images/ellipse-72-oYV.png
    - assets/page-1/images/ellipse-70-fDK.png
    - assets/page-1/images/ellipse-66-6T3.png
    - assets/page-1/images/notification.png
    - assets/page-1/images/icon-signal-strength-3-CxR.png
    - assets/page-1/images/ai-1.png
    - assets/page-1/images/f354007466mm4qila3n92ywpseqs82gbwxbb06r1i4-1.png
    - assets/page-1/images/icon-signal-strength-3-B6Z.png
    - assets/page-1/images/icon-signal-bars--XAR.png
    - assets/page-1/images/icon-signal-bars--E6m.png
    - assets/page-1/images/icon-battery-charge-100-full-B21.png
    - assets/page-1/images/icon-battery-charge-100-full-gUZ.png
    - assets/page-1/images/icon-battery-charge-100-full-3a1.png
    - assets/page-1/images/icon-signal-bars--cND.png
    - assets/page-1/images/arrowleft-Mqb.png
    - assets/page-1/images/arrowleft-Jkq.png
    - assets/page-1/images/notification-ZaH.png
    - assets/page-1/images/ellipse-66-1r9.png
    - assets/page-1/images/ellipse-67-eQZ.png
    - assets/page-1/images/icon-signal-bars--2UH.png
    - assets/page-1/images/icon-battery-charge-100-full-tmP.png
    - assets/page-1/images/icon-signal-bars--SD7.png
    - assets/page-1/images/icon-signal-strength-3-u1K.png
    - assets/page-1/images/icon-signal-strength-3-sEH.png
    - assets/page-1/images/icon-battery-charge-100-full-XoF.png
    - assets/page-1/images/notification-4aD.png
    - assets/page-1/images/icon-battery-charge-100-full-B7f.png
    - assets/page-1/images/icon-battery-charge-100-full-NsK.png
    - assets/page-1/images/icon-signal-bars--zuw.png
    - assets/page-1/images/frame-1.png
    - assets/page-1/images/icon-signal-bars--eoT.png
    - assets/page-1/images/expanddown-kdX.png
    - assets/page-1/images/arrowleft-hYm.png
    - assets/page-1/images/bellfill.png
    - assets/page-1/images/ellipse-68-Dn1.png
    - assets/page-1/images/signoutsqureduotone.png
    - assets/page-1/images/ellipse-73-7PX.png
    - assets/page-1/images/signoutsqureduotone-zdf.png
    - assets/page-1/images/rectangle.png
    - assets/page-1/images/icon-battery-charge-100-full-EX3.png
    - assets/page-1/images/bellfill-7bw.png
    - assets/page-1/images/programming-coding-1.png
    - assets/page-1/images/icon-signal-strength-3-Kgu.png
    - assets/page-1/images/rectangle-TTf.png
    - assets/page-1/images/expanddown-2Yh.png
    - assets/page-1/images/arrowleft-6YZ.png
    - assets/page-1/images/auto-group-8rvb.png
    - assets/page-1/images/untitled2-1.png
    - assets/page-1/images/ellipse-74-Q3T.png
    - assets/page-1/images/userfill-cad.png
    - assets/page-1/images/icon-battery-charge-100-full-G2u.png
    - assets/page-1/images/key.png
    - assets/page-1/images/google-1.png
    - assets/page-1/images/f354007466mm4qila3n92ywpseqs82gbwxbb06r1i4-2.png
    - assets/page-1/images/multiple-choice-icon-11-1.png
    - assets/page-1/images/icon-signal-strength-3-yy3.png
    - assets/page-1/images/practice-checker-1.png
    - assets/page-1/images/background.png
    - assets/page-1/images/viewhidefill-Gru.png
    - assets/page-1/images/viewhidefill-BZb.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
